config/routes.rb
ClassyLetters::Application.routes.draw do
  root :to => 'pages#home'

  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations" }

  match '/home'     => 'pages#home',     :as => :home,     :via => :get
  match '/about'    => 'pages#about',    :as => :about,    :via => :get
  match '/contact'  => 'pages#contact',  :as => :contact,  :via => :get
  match '/faq'      => 'pages#faq',      :as => :faq,      :via => :get
  match '/security' => 'pages#security', :as => :security, :via => :get

  resources :letter_orders do
    resource :purchase, :except => [:edit, :update, :destroy]
  end
  
  resources :purchased_orders, :only => [:index, :show] do
    member do
      put 'fulfilled'
    end
  end

end

app/controllers/purchased_orders_controller.rb
class PurchasedOrdersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :is_admin?
  
  # GET /purchased_orders
  def index
    if params[:uuid].present?
      uuid = params[:uuid].strip
      letter_order = LetterOrder.find_by_uuid(uuid)
      if letter_order.nil?
        flash.now[:alert] = "#{params[:uuid]} is an invalid uuid."
      else
        redirect_to purchased_order_path(uuid)
        return
      end
    end
    
    @letter_orders_purchased = LetterOrder.accessible_by(current_ability).
                                           where("delivery_status = 1").
                                           order("preferred_delivery_date ASC").
                                           paginate(:page => params[:purchased_page])
    @letter_orders_delivered = LetterOrder.accessible_by(current_ability).
                                           where("delivery_status = 2").
                                           order("updated_at DESC").
                                           paginate(:page => params[:delivered_page])
    
    if @letter_orders_purchased.empty? and @letter_orders_delivered.empty?
      flash[:notice] = "No letters have been purchased yet."
      redirect_to root_path
      return
    end

    respond_to do |format|
      format.html # index.html.erb
    end
  end
  
  # GET /purchased_orders/1
  def show
    @letter_order = LetterOrder.find_by_uuid(params[:id])

    if @letter_order.delivery_status == 0
      flash[:alert] = "Letter #{params[:id]} has not been purchased yet."
      redirect_to purchased_orders_path
      return
    end
    
    respond_to do |format|
      format.html
      format.json { render json: @letter_order }
    end
  end
  
  # PUT /purchased_orders/1/fulfilled
  def fulfilled
    @letter_order = LetterOrder.find_by_uuid(params[:id])
    error_free = @letter_order.set_delivery_status!(params[:delivery_status])
    if error_free == false
      flash[:error] = "You can't set the delivery status to #{params[:delivery_status]}" 
    else
      case @letter_order.delivery_status
      when 0
        flash[:notice] = "Letter Order #{params[:id]} has been set to draft."
      when 1
        flash[:notice] = "Letter Order #{params[:id]} has been set to purchased but not fulfilled."
      when 2
        flash[:notice] = "Letter Order #{params[:id]} has been set to fulfilled."
      end
    end
    
    redirect_to purchased_orders_path
  end
  
  private
  
  def is_admin?
    unless current_user.admin?
      flash[:alert] = "Sorry you're not an administrator."
      redirect_to root_path
    end
  end
end

app/helpers/purchased_orders_helper.rb
module PurchasedOrdersHelper
end

app/views/purchased_orders/_letter_order.html.erb
<strong>Serial Number:</strong> <%= link_to letter_order.uuid, purchased_order_path(letter_order.to_param) %> 
&nbsp 
<strong>Preferred Delivery Date:</strong> <%= letter_order.preferred_delivery_date %>
&nbsp 
<strong>Written On:</strong> <%= letter_order.created_at.to_date %>
&nbsp
<strong>Price:</strong> $<%= letter_order.price %>

<br/>

<strong>Delivery Address:</strong>
<%= letter_order.address_street1 %>,
<% unless letter_order.address_street2.blank? %>
  <%= letter_order.address_street2 %>,
<% end %>
<%= letter_order.address_city %>, <%= letter_order.address_state %>, <%= letter_order.address_zip %>

&nbsp
<%= link_to "Finalize Order", purchased_order_path(letter_order.to_param) %>

app/views/purchased_orders/index.html.erb
<div class="sixteen columns">
  <div class="row">
    <div class="eight columns alpha">
      <h2>Current Purchased Lettre Orders</h2>
    </div>
    <div class="eight columns right omega">
      <%# link_to 'New Lettre order', new_lettre_order_path, :class => "button" %>
      <%= form_tag purchased_orders_path, :method => :get, :class => "no-bottom pull-right full_width" do %>
        <%= text_field_tag :uuid, params[:uuid], :placeholder => "Look up uuid", :class => "half_width inline no-bottom" %>
        <%= submit_tag "Lookup", :class => "button no-bottom inline" %>
      <% end %>
    </div>
  </div>

  <!-- Standard <ul> with class of "tabs" -->
  <ul class="tabs">
    <!-- Give href an ID value of corresponding "tabs-content" <li>'s -->
    <li><a class="active" href="#not_delivered">Purchased, but not delivered yet (<%= @lettre_orders_purchased.count %>)</a></li>
    <li><a href="#delivered">Delivered (<%= @lettre_orders_delivered.count %>)</a></li>
  </ul>

  <!-- Standard <ul> with class of "tabs-content" -->
  <ul class="tabs-content">
    <li class="active" id="not_delivered">
      <% if @lettre_orders_purchased.nil? or @lettre_orders_purchased.empty? %>
        <div class="info">
          There aren't any purchased orders that haven't been delivered yet.
        </div>
      <% else %>
        <%= render :collection => @lettre_orders_purchased, :partial => "lettre_order", :as => "lettre_order", :spacer_template => "shared/spacer" %>
        <div class="center add-top">
          <%= will_paginate @lettre_orders_purchased, :param_name => :purchased_page, :params => { :anchor => "not_delivered" } %>
        </div>
      <% end %>
    </li>
    <li id="delivered">
      <% if @lettre_orders_delivered.nil? or @lettre_orders_delivered.empty? %>
        <div class="info">
          There aren't any purchased orders that have been delivered yet.
        </div>
      <% else %>
        <%= render :collection => @lettre_orders_delivered, :partial => "lettre_order", :as => "lettre_order", :spacer_template => "shared/spacer" %>
        <div class="center add-top">
          <%= will_paginate @lettre_orders_delivered, :param_name => :delivered_page, :params => { :anchor => "delivered" } %>
        </div>
      <% end %>      
    </li>
  </ul>
  
</div>

app/views/purchased_orders/show.html.erb
<div class="sixteen columns">
  <h2>Letter: &nbsp <%= @letter_order.uuid %></h2>
</div>
<div class="row">
  <div class="ten columns">
    <%= render 'letter_orders/letter_preview', :letter_order => @letter_order %>
  </div>

  <div class="six columns">
    <%= render 'letter_orders/address_preview', :letter_order => @letter_order %>

    <%= render 'letter_orders/delivery_options', :letter_order => @letter_order %>

    <%= render 'letter_orders/price_and_subtotal', :letter_order => @letter_order %>
    
    <div class="add-top">
      <% if @letter_order.delivery_status == 1 %>
        <%= link_to "I fulfilled this order", fulfilled_purchased_order_path(@letter_order.to_param, :delivery_status => 2), :method => :put %>
      <% else %>
        <%= link_to "Set to purchased but not fulfilled", fulfilled_purchased_order_path(@letter_order.to_param, :delivery_status => 1), :method => :put %>
      <% end %>
      | <%= link_to "Back to purchased orders", purchased_orders_path %>
    </div>
  </div>
</div>