config/routes.rb
ClassyLetters::Application.routes.draw do
  root :to => 'pages#home'

  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations" }

  match '/home'     => 'pages#home',     :as => :home,     :via => :get
  match '/about'    => 'pages#about',    :as => :about,    :via => :get
  match '/contact'  => 'pages#contact',  :as => :contact,  :via => :get
  match '/faq'      => 'pages#faq',      :as => :faq,      :via => :get
  match '/security' => 'pages#security', :as => :security, :via => :get

  resources :letter_orders do
    resource :purchase, :except => [:edit, :update, :destroy]
  end
  
  resources :purchased_orders, :only => [:index, :show] do
    member do
      put 'fulfilled'
    end
  end

end

app/models/letter_order.rb
# == Schema Information
# Schema version: 20120419205958
#
# Table name: letter_orders
#
#  id                      :integer         not null, primary key
#  user_id                 :integer
#  preferred_delivery_date :date
#  signed_name             :string(255)
#  message_display_date    :date
#  message                 :text
#  created_at              :datetime        not null
#  updated_at              :datetime        not null
#  address_street1         :string(255)
#  address_street2         :string(255)
#  address_city            :string(255)
#  address_state           :string(255)
#  address_zip             :string(255)
#  paper_size              :integer         default(0)
#  writing_style           :integer         default(0)
#  wax_seal                :boolean         default(FALSE)
#  uuid                    :string(255)
#  doodle                  :boolean         default(FALSE)
#  lipstick                :boolean         default(FALSE)
#  teardrops               :boolean         default(FALSE)
#  in_person               :boolean         default(FALSE)
#  delivery_status         :integer         default(0)
#  assigned_user_id        :integer
#

class LetterOrder < ActiveRecord::Base
  attr_accessible :message, :message_display_date, :preferred_delivery_date, :signed_name
  attr_accessible :address_street1, :address_street2, :address_city, :address_state, :address_zip
  attr_accessible :paper_size, :writing_style, :wax_seal
  attr_accessible :doodle, :lipstick, :teardrops, :in_person
    
  validates_presence_of :message
  validates_presence_of :preferred_delivery_date
  validate :in_the_future  
  validates_presence_of :user_id
  
  validates_presence_of :address_street1
  validates_presence_of :address_city
  validates_presence_of :address_state
  validates_format_of :address_state, :with => /^(A[LKSZRAEP]|C[AOT]|D[EC]|F[LM]|G[AU]|HI|I[ADLN]|K[SY]|LA|M[ADEHINOPST]|N[CDEHJMVY]|O[HKR]|P[ARW]|RI|S[CD]|T[NX]|UT|V[AIT]|W[AIVY])$/
  # For a reference on the zip codes http://en.wikipedia.org/wiki/ZIP_code
  # For a reference for the regex http://regexlib.com/REDetails.aspx?regexp_id=471&AspxAutoDetectCookieSupport=1
  validates_presence_of :address_zip
  validates_format_of :address_zip, :with => /^[0-9]{5}(-[0-9]{4})?$/
  
  validates_inclusion_of :paper_size, :in => 0..2
  validates_inclusion_of :writing_style, :in => 0..2
  
  validates_presence_of :uuid
  validates_uniqueness_of :uuid, :message => "must be unique"
  
  belongs_to :user
  
  validates_inclusion_of :delivery_status, :in => 0..2 # 0 = draft; 1 = purchased; 2 = delivered
  belongs_to :assigned_user, :class_name => "User", :foreign_key => "assigned_user_id"
  
  has_one :purchase
  
  def to_param
    uuid
  end
  
  def display_message
    message.gsub(/\n/, '<br/>').html_safe
  end
  
  def price
    subtotal = 8.99 # base price
    case paper_size
    when 1
      subtotal += 2 # medium
    when 2
      subtotal += 5 # large
    end
    
    case writing_style
    when 1
      subtotal += 5 # hand written
    when 2
      subtotal += 10 # calligraphy
    end
    
    subtotal += 2 if wax_seal
    subtotal += 3 if doodle
    subtotal += 1 if lipstick
    subtotal += 1 if teardrops
    subtotal += 20 if in_person

    subtotal += extra_charge_for_characters
    return subtotal.round(2)
  end
  
  def extra_charge_for_characters
    per_char = 2 # number of cents
    if message.length > 500
      ((message.length - 500).abs * (per_char / 100.to_f) )
    else
      0
    end
  end
  
  def has_extras?
    wax_seal || doodle || lipstick || teardrops || in_person
  end
  
  def extras_list
    res = []
    res << "Wax Seal" if wax_seal
    res << "Doodle" if doodle
    res << "Lipstick" if lipstick
    res << "Tear Drops" if teardrops
    res << "In Person Delivery" if in_person
    return res
  end
  
  def set_delivery_status!(new_status)
    int_status = new_status.to_i
    self.delivery_status = int_status
    self.save(:validate => false)
  end
    
  private
  
  def in_the_future
    buffer = 2.days
    unless preferred_delivery_date.nil?
      # if created_at 
      #   temp_date = created_at.to_date + buffer
      #   if preferred_delivery_date < temp_date
      #     errors.add(:preferred_delivery_date, "is unrealistic please choose a date after #{(created_at + buffer).strftime("%b %d %Y")}")
      #     return
      #   else
      #     return
      #   end
      # end
      
      if preferred_delivery_date < Time.now.to_date + buffer
        errors.add(:preferred_delivery_date, "is unrealistic please choose a date after #{(Time.now + buffer).strftime("%b %d %Y")}")
      end
    end
  end
end

app/controllers/letter_orders_controller.rb
class LetterOrdersController < ApplicationController
  before_filter :authenticate_user!

  # GET /letter_orders
  # GET /letter_orders.json
  def index
    @letter_order_drafts     = current_user.letter_orders.where("delivery_status = 0").
                                                          order("updated_at desc").paginate(:page => params[:drafts_page])
    @letter_orders_purchased = current_user.letter_orders.where("delivery_status = 1").
                                                          order("updated_at desc").paginate(:page => params[:purchased_page])
    @letter_orders_delivered = current_user.letter_orders.where("delivery_status = 2").
                                                          order("updated_at desc").paginate(:page => params[:delivered_page])
    
    if @letter_order_drafts.empty? and @letter_orders_purchased.empty? and @letter_orders_delivered.empty?
      flash[:notice] = "You haven't written any letters yet."
      redirect_to :action => :new
      return
    end

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /letter_orders/1
  # GET /letter_orders/1.json
  def show
    @letter_order = LetterOrder.find_by_uuid(params[:id])

    authorize! :show, @letter_order

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @letter_order }
    end
  end

  # GET /letter_orders/new
  # GET /letter_orders/new.json
  def new
    @letter_order = LetterOrder.new
    @letter_order.preferred_delivery_date = (Time.now + 3.days).strftime("%b %d %Y")
    @letter_order.message_display_date = Time.now.strftime("%b %d %Y")

    authorize! :new, LetterOrder

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @letter_order }
    end
  end

  # GET /letter_orders/1/edit
  def edit
    @letter_order = LetterOrder.find_by_uuid(params[:id])
    
    authorize! :edit, @letter_order
  end

  # POST /letter_orders
  # POST /letter_orders.json
  def create
    @letter_order = current_user.letter_orders.build(params[:letter_order])
    @letter_order.uuid = SecureRandom.uuid

    authorize! :create, LetterOrder

    respond_to do |format|
      if @letter_order.save
        format.html { redirect_to @letter_order, notice: 'Letter order was successfully created.' }
        format.json { render json: @letter_order, status: :created, location: @letter_order }
      else
        format.html { render action: "new" }
        format.json { render json: @letter_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /letter_orders/1
  # PUT /letter_orders/1.json
  def update
    @letter_order = LetterOrder.find_by_uuid(params[:id])

    authorize! :update, @letter_order

    respond_to do |format|
      if @letter_order.update_attributes(params[:letter_order])
        format.html { redirect_to @letter_order, notice: 'Letter order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @letter_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /letter_orders/1
  # DELETE /letter_orders/1.json
  def destroy
    @letter_order = LetterOrder.find_by_uuid(params[:id])
    authorize! :destroy, @letter_order

    @letter_order.destroy

    respond_to do |format|
      format.html { redirect_to letter_orders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/letter_orders_helper.rb
module LetterOrdersHelper
end

app/views/letter_orders/_address_preview.html.erb
<div class="well letter_message add-bottom">
  <strong>Mail Address:</strong><br/>
  <%= letter_order.address_street1 %><br/>
  <% unless letter_order.address_street2.blank? %>
    <%= letter_order.address_street2 %><br/>
  <% end %>
  <%= letter_order.address_city %>, <%= letter_order.address_state %>, <%= letter_order.address_zip %>
</div>

app/views/letter_orders/_delivery_options.html.erb
<h4>Delivery Options</h4>
<div class="add-bottom">
  <strong>Preferred Delivery Date:</strong> <%= letter_order.preferred_delivery_date.strftime("%b %d %Y") %><br/>
  <strong>Page size:</strong> <%= render 'letter_orders/paper_size', :paper_size => letter_order.paper_size %> &nbsp &nbsp
  <strong>Handwriting:</strong> <%= render 'letter_orders/writing_style', :writing_style => letter_order.writing_style %><br/>
  <%= render 'letter_orders/order_status', :letter_order => letter_order %><br/>
  <% if letter_order.has_extras? %>
    <strong>Extras:</strong> <%= render 'letter_orders/extras_list', :letter_order => letter_order %>
  <% end %>
</div>

app/views/letter_orders/_extras_list.html.erb
<%= letter_order.extras_list.to_sentence %>

app/views/letter_orders/_form.html.erb
<%= form_for(@letter_order) do |f| %>
  <div class="row">
    <div class="ten columns">
      <%= render "shared/error_messages", :object => f.object %>
      <%= f.text_area :message, :class => "full_width letter_message remove-bottom", :rows => 15 %>
      <p>
        <span id="message_char_count">Base rate includes 500 more characters. You will be charged $0.05/character over the limit.</span>
      </p>

      <div class="three columns alpha">
        <%= f.label :signed_name %>
        <%= f.text_field :signed_name, :class => "width100" %>
      </div>
      
      <div class="three columns">
        <%= f.label :preferred_delivery_date %>
        <%= f.text_field :preferred_delivery_date, :class => "date_input width100", 
                         :placeholder => "i.e. \"#{(Time.now + 2.days).strftime("%b %d %Y")}\"" %>
      </div>
      
      <div class="three columns omega">
        <%= f.label :message_display_date %>
        <%= f.text_field :message_display_date, :class => "date_input width100", 
                         :placeholder => "i.e. \"#{(Time.now).strftime("%b %d %Y")}\"" %>
      </div>
    </div>
    
    <div class="six columns">
      <h4>Delivery Address</h4>
      <%= f.text_field :address_street1, :class => "width100", :placeholder => "Street Address1 (ie 500 Main Street)" %>
      <%= f.text_field :address_street2, :class => "width100", :placeholder => "Street Address2 (ie Apt #3b or Suite 300) (optional)" %>
      <div class="three columns alpha">
        <%= f.text_field :address_city, :class => "width100", :placeholder => "City" %>
      </div>
      <div class="one column">
        <%= f.text_field :address_state, :class => "width100 make_upcase", :placeholder => "State", :maxlength => 2 %>
      </div>
      <div class="two columns omega">
        <%= f.text_field :address_zip, :class => "width100", :placeholder => "Zip Code", :maxlength => 10 %>
      </div>

      <h4>Paper Size</h4>
      <div class="half-bottom">
        <label class="inline">
          <%= f.radio_button :paper_size, 0, :checked => true %>
          <span><%= render 'letter_orders/paper_size', :paper_size => 0 %></span>
        </label>
      
        <label class="inline">
          <%= f.radio_button :paper_size, 1 %>
          <span><%= render 'letter_orders/paper_size', :paper_size => 1 %> <strong>add $2</strong></span>
        </label>
      
        <label class="inline">
          <%= f.radio_button :paper_size, 2 %>
          <span><%= render 'letter_orders/paper_size', :paper_size => 2 %> <strong>add $5</strong></span>
        </label>
      </div>
      
        <h4>Handwriting</h4>
        <div class="half-bottom">
          <label class="inline">
            <%= f.radio_button :writing_style, 0, :checked => true %>
            <span><%= render 'letter_orders/writing_style', :writing_style => 0 %></span>
          </label>
        
          <label class="inline">
            <%= f.radio_button :writing_style, 1 %>
            <span><%= render 'letter_orders/writing_style', :writing_style => 1 %> <strong>add $5</strong></span>
          </label>
        
          <label class="inline">
            <%= f.radio_button :writing_style, 2 %>
            <span><%= render 'letter_orders/writing_style', :writing_style => 2 %> <strong>add $10</strong></span>
          </label>
        </div>
        
        <div><%= f.check_box :wax_seal %> <%= f.label :wax_seal, "Add $2 for a wax seal on the envelope" %></div>
        <div><%= f.check_box :doodle %> <%= f.label :doodle, "Add $3 for a doodled border" %></div>
        <div><%= f.check_box :lipstick %> <%= f.label :lipstick, "Add $1 for a lipstick kiss on the envelope" %></div>
        <div><%= f.check_box :teardrops %> <%= f.label :teardrops, "Add $1 for teardrops on the stationary" %></div>
        <div><%= f.check_box :in_person %> <%= f.label :in_person, "Add $20 for in person delivery (only Silicon Valley)" %></div>

        <div class="add-top">
          <%= f.submit %>
          <span>
            <% if params[:action] == "edit" %>
              &nbsp <%= link_to "Cancel", @letter_order %>
            <% end %>
            &nbsp <%= link_to "Back to my letters", letter_orders_path %> 
          </span>
        </div>
      </div>    
    </div>
  </div>
<% end %>

app/views/letter_orders/_letter_order.html.erb
<strong>Serial Number:</strong> <%= link_to letter_order.uuid, letter_order %> 
&nbsp 
<strong>Preferred Delivery Date:</strong> <%= letter_order.preferred_delivery_date %>
&nbsp 
<strong>Written On:</strong> <%= letter_order.created_at.to_date %>
&nbsp
<strong>Price:</strong> $<%= letter_order.price %>

<br/>

<strong>Delivery Address:</strong>
<%= letter_order.address_street1 %>,
<% unless letter_order.address_street2.blank? %>
  <%= letter_order.address_street2 %>,
<% end %>
<%= letter_order.address_city %>, <%= letter_order.address_state %>, <%= letter_order.address_zip %>

&nbsp
<% if letter_order.delivery_status == 0 %>
  <%= link_to "Finalize Purchase", letter_order %>
<% else %>
  <%= link_to "View Receipt", letter_order_purchase_path(letter_order) %>
<% end %>

<% if can? :edit, letter_order %>
  &nbsp
  <%= link_to "Edit Letter", edit_letter_order_path(letter_order) %>
<% end %>

app/views/letter_orders/_letter_preview.html.erb
<div class="well">
  <div class="vertical-buffer-large"></div>
  <div class="letter_message"><%= letter_order.message_display_date.strftime("%b %d %Y") %></div>
  <div class="letter_message"><%= letter_order.display_message %></div>
  <% unless letter_order.signed_name.blank? %>
    <div class="letter_message" id="stylized_sig"><strong><%= letter_order.signed_name %></strong></div>
  <% end %>
  <div class="vertical-buffer-large"></div>
</div>

app/views/letter_orders/_paper_size.html.erb
<% case paper_size %>
<% when 0 %>
  Small
<% when 1 %>
  Medium
<% when 2 %>
  Large
<% end %>

app/views/letter_orders/_price_and_subtotal.html.erb
<div class="add-bottom hidden" id="subtotals">
  <h5>Subtotal</h5>
  <%= render 'letter_orders/subtotals', :letter_order => letter_order %>
</div>

<h4 class="inline">Total Price: $<%= letter_order.price %></h4> - 
  <span><%= link_to "show subtotals", "#", :id => "subtotal_toggle" %></span>

app/views/letter_orders/_subtotals.html.erb
<table class="half_width">
  <thead>
    <tr>
      <th></th>
      <th>Price</th>
    </tr>
  </thead>
  
  <tbody class="center">
    <tr>
      <td>Base rate</td>
      <td>$8.99</td>
    </tr>
    
    <% if letter_order.paper_size > 0 %>
      <% if letter_order.paper_size == 1 %>
        <tr>
          <td>Cursive</td>
          <td>$5.00</td>
        </tr>
      <% end %>
      
      <% if letter_order.paper_size == 2 %>
        <tr>
          <td>Calligraphy</td>
          <td>$10.00</td>
        </tr>
      <% end %>
    <% end %>
    
    <% if letter_order.writing_style > 0 %>
      <% if letter_order.writing_style == 1 %>
        <tr>
          <td>Medium Paper</td>
          <td>$2.00</td>
        </tr>
      <% end %>
    
      <% if letter_order.writing_style == 2 %>
        <tr>
          <td>Large Paper</td>
          <td>$5.00</td>
        </tr>
      <% end %>
    <% end %>
    
    <% if letter_order.wax_seal %>
      <tr>
        <td>Wax Seal</td>
        <td>$2.00</td>
      </tr>
    <% end %>
    
    <% if letter_order.doodle %>
      <tr>
        <td>Doodle</td>
        <td>$3.00</td>
      </tr>
    <% end %>
    
    <% if letter_order.lipstick %>
      <tr>
        <td>Lipstick</td>
        <td>$1.00</td>
      </tr>
    <% end %>
    
    <% if letter_order.teardrops %>
      <tr>
        <td>Tear Drops</td>
        <td>$1.00</td>
      </tr>
    <% end %>
    
    <% if letter_order.in_person %>
      <tr>
        <td>In Person Delivery</td>
        <td>$20.00</td>
      </tr>
    <% end %>
    
    <% if letter_order.extra_charge_for_characters > 0 %>
      <tr>
        <td><%= pluralize(letter_order.message.length - 500, "Extra Character") %></td>
        <td>$<%= "%.2f" % letter_order.extra_charge_for_characters %></td>
      </tr>
    <% end %>
    
    <tr class="top-border">
      <td><strong>Total Price</strong></td>
      <td><strong>$<%= letter_order.price %></strong></td>
    </tr>
  </tbody>
  
</table>

app/views/letter_orders/_writing_style.html.erb
<% case writing_style %>
<% when 0 %>
  Print
<% when 1 %>
  Cursive
<% when 2 %>
  Calligraphy
<% end %>

app/views/letter_orders/edit.html.erb
<div class="row remove-bottom">
  <div class="sixteen columns">
    <h2>Edit Letter</h2>
  </div>
</div>

<%= render 'form' %>

app/views/letter_orders/index.html.erb
<div class="sixteen columns">
  <div class="eight columns alpha">
    <h2>My Letter Orders</h2>
  </div>
  <div class="eight columns right omega">
    <%= link_to 'New Letter order', new_letter_order_path, :class => "button" %>
  </div>

  <!-- Standard <ul> with class of "tabs" -->
  <ul class="tabs">
    <!-- Give href an ID value of corresponding "tabs-content" <li>'s -->
    <li><a class="active" href="#drafts">Drafts (<%= @letter_order_drafts.count %>)</a></li>
    <li><a href="#not_delivered">Purchased, but not delivered yet (<%= @letter_orders_purchased.count %>)</a></li>
    <li><a href="#delivered">Delivered (<%= @letter_orders_delivered.count %>)</a></li>
  </ul>

  <!-- Standard <ul> with class of "tabs-content" -->
  <ul class="tabs-content">
    <!-- Give ID that matches HREF of above anchors -->
    <li class="active" id="drafts">
      <% if @letter_order_drafts.nil? or @letter_order_drafts.empty? %>
        <div class="info">
          You don't have any drafts for letter orders right now.
        </div>
      <% else %>
        <%= render :collection => @letter_order_drafts, :partial => "letter_order", :as => "letter_order", :spacer_template => "shared/spacer" %>
        <div class="center add-top">
          <%= will_paginate @letter_order_drafts, :param_name => :drafts_page, :params => { :anchor => "drafts" } %>
        </div>
      <% end %>
    </li>
    <li id="not_delivered">
      <% if @letter_orders_purchased.nil? or @letter_orders_purchased.empty? %>
        <div class="info">
          You don't have any purchased orders that haven't been delivered yet.
        </div>
      <% else %>
        <%= render :collection => @letter_orders_purchased, :partial => "letter_order", :as => "letter_order", :spacer_template => "shared/spacer" %>
        <div class="center add-top">
          <%= will_paginate @letter_orders_purchased, :param_name => :purchased_page, :params => { :anchor => "not_delivered" } %>
        </div>
      <% end %>
    </li>
    <li id="delivered">
      <% if @letter_orders_delivered.nil? or @letter_orders_delivered.empty? %>
        <div class="info">
          You don't have any purchased orders that have been delivered yet.
        </div>
      <% else %>
        <%= render :collection => @letter_orders_delivered, :partial => "letter_order", :as => "letter_order", :spacer_template => "shared/spacer" %>
        <div class="center add-top">
          <%= will_paginate @letter_orders_delivered, :param_name => :delivered_page, :params => { :anchor => "delivered" } %>
        </div>
      <% end %>      
    </li>
  </ul>
  
</div>

app/views/letter_orders/new.html.erb
<div class="row remove-bottom">
  <div class="sixteen columns">
    <h2>New Letter</h2>
  </div>
</div>

<%= render 'form' %>

app/views/letter_orders/show.html.erb
<div class="sixteen columns">
  <h2>Letter: &nbsp <%= @letter_order.uuid %></h2>
</div>
<div class="row">
  <div class="ten columns">
    <div class="right-buffer">
      <%= render 'letter_orders/letter_preview', :letter_order => @letter_order %>
    </div>
  </div>

  <div class="six columns">
    <%= render 'letter_orders/address_preview', :letter_order => @letter_order %>

    <%= render 'letter_orders/delivery_options', :letter_order => @letter_order %>

    <%= render 'letter_orders/price_and_subtotal', :letter_order => @letter_order %>
    
    <div>
      <% if @letter_order.delivery_status == 0 %>
        <%= link_to "Purchase and Send", new_letter_order_purchase_path(@letter_order), :class => "button" %>
      <% else %>
        <%= link_to "View Receipt", letter_order_purchase_path(@letter_order), :class => "button" %>
      <% end %>
      <p>Once you purchase your order you will no longer be able to make any changes.</p>
    </div>
    
    <% if can? :manage, @letter_order %>
      <%= link_to 'Edit Order', edit_letter_order_path(@letter_order) %> | <%= link_to 'Delete Order', @letter_order, confirm: 'Are you sure?', method: :delete %> |
    <% end %>
    <%= link_to 'Back to my Letter Orders', letter_orders_path %>
  </div>
</div>