config/routes.rb
ClassyLetters::Application.routes.draw do
  root :to => 'pages#home'

  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations" }

  match '/home'     => 'pages#home',     :as => :home,     :via => :get
  match '/about'    => 'pages#about',    :as => :about,    :via => :get
  match '/contact'  => 'pages#contact',  :as => :contact,  :via => :get
  match '/faq'      => 'pages#faq',      :as => :faq,      :via => :get
  match '/security' => 'pages#security', :as => :security, :via => :get

  resources :letter_orders do
    resource :purchase, :except => [:edit, :update, :destroy]
  end
  
  resources :purchased_orders, :only => [:index, :show] do
    member do
      put 'fulfilled'
    end
  end

end

app/views/pages/_open_graph.html.erb
<%= content_for :head do %>
  <meta property="og:title" content="Classy Letters"/>
  <meta property="og:description" content="Classy Letters is an easy way to send a unique handwritten letter without having to go to the post office."/>
  <meta property="og:url" content="http://classyletters.com/"/>
  <meta property="og:site_name" content="Classy Letters"/>
  <meta property="og:type" content="website"/>
<% end %>

app/views/pages/_sign_up_or_compose.html.erb
<h4><strong>
  <% if signed_in? %>
    <%= link_to "Compose Your Next Classy Letter", new_letter_order_path %> 
  <% else %>
    <%= link_to "Sign up now!", new_user_registration_path %>
  <% end %>
</strong></h4>

app/views/pages/about.html.erb
<%= render :partial => 'open_graph' %>

<div class="row">
  <div class="ten columns justify">
    <h2>About</h2>
    <h4>How did this all get started?</h4>
    <p>
      I am really close with my grandmother. When I moved to the east coast for college, it was really hard for me to communicate with her.
      Because she's technophobic, I would email my mom and have her print out my emails for my grandmother. 
      My brother puts me to shame; he is a regular pen pal with our grandmother.
    </p>
    
    <h4>My wish</h4>
    <p>
      I wish there had been a way for me to easily send snail mail letters to my grandmother, so she could have the excitement of getting my
      letter in the mail.
    </p>
    
    <p>
      Then it hit me. Getting mail is exciting. The problem is that it takes so much more effort than just shooting off an email. Why not make
      it super easy for people to be able to send unique snail mail letters to one another?
    </p>
    
    <h4>Here's the Plan</h4>
    <p>
      <strong>Classy Letters</strong> is going to start with a few offerings:
    </p>
    <ol>
      <li>Handwritten message on nice stationary (print, cursive, or calligraphy)</li>
      <li>Wax seal the envelope</li>
      <li>Doodled border</li>
      <li>Lipstick kiss on the letter</li>
      <li>Teardrops on the stationary</li>
      <li>In-person delivery</li>
    </ol>
    
    <div class="center">
      <%= render :partial => 'sign_up_or_compose' %>
    </div>
  </div>
  
  <div class="six columns">
    <%= render 'shared/addthis' %>
  </div>
</div>

app/views/pages/contact.html.erb
<%= render :partial => 'open_graph' %>

<div class="row">
  <div class="sixteen columns">
    <h2>Contact Us</h2>
  </div>
  <div class="five columns">
    <blockquote>
      <h5>Phone</h5>
      (415) 867-2705<br>
      <hr/>
      <h5>Snail Mail</h5>
      776 University Ave.<br>
      Palo Alto, CA 94301<br>
      <hr>
      <h5>Twitter</h5>
      <%= link_to "@myclassyletters", "http://www.twitter.com/myclassyletters", :target => "_blank" %>
      <hr>
      <%= render 'shared/addthis' %>
    </blockquote>
  </div>
  <div class="eleven columns">
    <h4>Team</h4>
    <h5>Cyrus Stoller</h5>
    <p>
      Cyrus is old school. He wears loafers, drinks martinis, and writes letters by hand. But Cyrus is living in a new school world,
      where stamps and stationary are hard to come by and the postman only rings once a day.
      Now Cyrus can send hand-crafted, personalized letters any time.
    </p>
    
    <h5>Ezra Stoller</h5>
    <p>
      Ezra is what you might call, "the creative one." He is an accomplished Chinese brush painter and writes cursive to rival elementary 
      school teachers. A sentimentalist at heart, he knows the importance of sending a Classy Letter.
    </p>
    
    <div class="center">
      <%= image_tag "supplies.png", :class => "supplies" %><br>
      <small>Photo Credit: Eric Cooperman</small>
    </div>
  </div>
</div>

app/views/pages/faq.html.erb
<%= render :partial => 'open_graph' %>

<div class="row">
  <div class="ten columns justify">
    <h2>Frequently Asked Questions</h2>
    <ul class="square">
      <li>
        <h4>Aren't there tons of other companies that make customized cards?</h4>
        <p>
          There are. <strong>Classy Letters</strong> is about writing personal letters, not buying Hallmark knockoffs.
        </p>
      </li>
      
      <li>
        <h4>How much does this cost?</h4>
        <p>The basic letter is US$ 8.99. That includes all of the supplies and postage.</p>
      </li>
      
      <li>
        <h4>Can I send a letter anonymously?</h4>
        <p>If you really want to, though we think you'll want to take credit for it.</p>
      </li>
      
      <li>
        <h4>Will you check my spelling / grammar?</h4>
        <p>
          Your message will be delivered verbatim. 
          Some of our clients add intentional misspellings to make their letters feel more authentic.
        </p>
      </li>
      
      <li>
        <h4>Couldn't I just do this on my own?</h4>
        <p>
          Odds are that your time is worth more than the US$ 8.99 that we're charging you to send a Classy Letter for a special occasion.
        </p>
      </li>
      
      <li>
        <h4>Is it safe to enter my credit card number?</h4>
        <p>
          Short answer is yes. If you want more information click <%= link_to "here", security_path %>.
        </p>
      </li>    
    </ul>
  </div>
  <div class="six columns">
    <%= render 'shared/addthis' %>
  </div>
</div>

app/views/pages/home.html.erb
<%= render :partial => 'open_graph' %>

<div class="row">
  <div class="vertical-buffer-large" />
  <div class="sixteen columns center">
    <h3>
      No two letters are the same.
    </h3>
    
    <h3>
      Leave a lasting impression.
    </h3>
  </div>

</div>


<div class="row">
  <div class="sixteen columns">
    <div class="vertical-buffer-large"></div>
    
    <blockquote>
      <p class="justify">
        <strong>Classy Letters</strong> is an easy way to send a unique handwritten letter without having to go to the post office.
      
        Whether it's a "Thank you," a special card to Mom on Mother's day, or a love letter to your special someone, 
        they'll be talking about this Classy Letter for a long time. 
      
        Show your colleagues, family, and friends that you care.
      </p>
    </blockquote>
  </div>
</div>

<div class="row">
  <div class="one-third column center">
    <div class="flash info">
      1. Compose your <strong><%= link_to "Letter", new_letter_order_path %></strong>
    </div>
  </div>
  <div class="one-third column center">
    <div class="flash info">
      2. Customize your <strong><%= link_to "Delivery", letter_orders_path %></strong>
    </div>
  </div>
  <div class="one-third column center">
    <div class="flash info">
      3. Wait for a grateful <strong><%= link_to "Response", about_path %></strong>
    </div>
  </div>
  
  <div class="sixteen columns center add-top">
    <%= render :partial => 'sign_up_or_compose' %>
    <div class="pull-right">
      <%= render 'shared/addthis' %>
    </div>
  </div>
</div>

app/views/pages/security.html.erb
<div class="row">
  <div class="ten columns justify">
    <h2>Security</h2>
    <p>We take your privacy seriously. We're using <%= link_to "Stripe", "https://stripe.com/gallery" %> to power our payments and keep your credit card information secure.</p>
    
    <p>Your credit card number is never stored on our servers. Your credit card number is processed by Stripe, which is PCI compliant. All of our web traffic uses SSL.</p>
    
    <h4>Other sites using Stripe</h4>
    
    <p>
      <%= link_to "Click here", "https://stripe.com/gallery" %>
    </p>
    
    <h4>SSL</h4>
    <p>We use SSL to encrypt all of our web traffic. On the web, SSL tries to do two things:
      <ol>
        <li>Encrypt and <%= link_to "verify the integrity", "http://en.wikipedia.org/wiki/Message_authentication_code" %> of traffic between the browser and the server.</li>
        <li>Verify that the browser is talking to the correct server. In practice, this usually means verifying that the owner of the domain and the owner of the server are the same entity. This helps prevent <%= link_to "man-in-the-middle", "http://en.wikipedia.org/wiki/Man-in-the-middle_attack" %> attacks. Without it there's no guarantee that you're encrypting traffic to the right recipient.</li>
      </ol>
      <small>Credit: <%= link_to "https://stripe.com/help/ssl" %></small>
    </p>
    
  </div>
  <div class="six columns">
  </div>
</div>