config/routes.rb
ClassyLetters::Application.routes.draw do
  root :to => 'pages#home'

  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations" }

  match '/home'     => 'pages#home',     :as => :home,     :via => :get
  match '/about'    => 'pages#about',    :as => :about,    :via => :get
  match '/contact'  => 'pages#contact',  :as => :contact,  :via => :get
  match '/faq'      => 'pages#faq',      :as => :faq,      :via => :get
  match '/security' => 'pages#security', :as => :security, :via => :get

  resources :letter_orders do
    resource :purchase, :except => [:edit, :update, :destroy]
  end
  
  resources :purchased_orders, :only => [:index, :show] do
    member do
      put 'fulfilled'
    end
  end

end

app/views/layouts/_footer.html.erb
<%= debug(params) if Rails.env.development? %>
<%= ENV.keys if Rails.env.development? %>

<!-- begin olark code --><script type='text/javascript'>/*{literal}<![CDATA[*/
window.olark||(function(c){var f=window,d=document,l=f.location.protocol=="https:"?"https:":"http:",z=c.name,r="load";var nt=function(){f[z]=function(){(a.s=a.s||[]).push(arguments)};var a=f[z]._={},q=c.methods.length;while(q--){(function(n){f[z][n]=function(){f[z]("call",n,arguments)}})(c.methods[q])}a.l=c.loader;a.i=nt;a.p={0:+new Date};a.P=function(u){a.p[u]=new Date-a.p[0]};function s(){a.P(r);f[z](r)}f.addEventListener?f.addEventListener(r,s,false):f.attachEvent("on"+r,s);var ld=function(){function p(hd){hd="head";return["<",hd,"></",hd,"><",i,' onl' + 'oad="var d=',g,";d.getElementsByTagName('head')[0].",j,"(d.",h,"('script')).",k,"='",l,"//",a.l,"'",'"',"></",i,">"].join("")}var i="body",m=d[i];if(!m){return setTimeout(ld,100)}a.P(1);var j="appendChild",h="createElement",k="src",n=d[h]("div"),v=n[j](d[h](z)),b=d[h]("iframe"),g="document",e="domain",o;n.style.display="none";m.insertBefore(n,m.firstChild).id=z;b.frameBorder="0";b.id=z+"-loader";if(/MSIE[ ]+6/.test(navigator.userAgent)){b.src="javascript:false"}b.allowTransparency="true";v[j](b);try{b.contentWindow[g].open()}catch(w){c[e]=d[e];o="javascript:var d="+g+".open();d.domain='"+d.domain+"';";b[k]=o+"void(0);"}try{var t=b.contentWindow[g];t.write(p());t.close()}catch(x){b[k]=o+'d.write("'+p().replace(/"/g,String.fromCharCode(92)+'"')+'");d.close();'}a.P(2)};ld()};nt()})({loader: "static.olark.com/jsclient/loader0.js",name:"olark",methods:["configure","extend","declare","identify"]});
/* custom configuration goes here (www.olark.com/documentation) */
olark.identify('3166-251-10-3900');/*]]>{/literal}*/</script>
<!-- end olark code -->

app/views/layouts/_header.html.erb
<div id="masthead" class="half-bottom"> 
  <div class="container remove-bottom"> 
    <div class="six chubby columns"> 
      <h1 class="remove-bottom"><strong><%= link_to "Classy Letters", root_path %></strong></h1> 
    </div>
    <div class="ten chubby columns right add-top">
      <ul class="inline">
        <% if signed_in? %>
          <li><%= link_to "Hi, #{current_user.display_name}", edit_user_registration_path %></li>
          <% if current_user.admin? %>
            <li><%= link_to "Dashboard (#{LetterOrder.where("delivery_status = 1").count})", purchased_orders_path %></li>
          <% end %>
        <% end %>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact Us", contact_path %></li>
        <li><%= link_to "FAQ", faq_path %></li>
        <% if signed_in? %>
          <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>


<hr class="top-line"/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <link href='https://fonts.googleapis.com/css?family=Rokkitt|Gochi+Hand' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= yield :stripe_js %>
  <%= yield :head %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_API_KEY %>
  <% if Rails.env.production? %>
    <%= render 'shared/google_analytics' %>
  <% end %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
  <div class="sixteen columns">
    <% flash.each do |key, value| %>
    <div class="flash <%= key %> add-top">
      <%= value %>
    </div>
    <% end %>
  </div>
</div>

<div class="container">
  <%= yield %>
</div>

<%= render 'layouts/footer' %>

<!-- External Javacript -->
<%= yield :footer %>

</body>
</html>